export const apiUrls = {
  dashboardTariffs: '/api/v1/internet-tariffs',
  dashboardCategories: '/api/v1/internet-tariff-categories',
  fileUrl: '/api/v1/minio/upload/files',
  imageUrl: '/api/v1/minio/upload/image',
  navigationCards: '/api/v1/cards',
  stories: '/api/v2/stories/dashboard',
  news: '/api/v1/news',
  chatMessages: '/api/message/v1/chatMessages',
  chatsActiveChats: '/api/chat/v1/activeChats',
  callBackRequests: '/api/v1/dashboard/applications',
  channels: '/api/v1/channels',
  channelCategories: '/api/v1/channel-categories',
  channelTariffs: '/api/v1/channel-tariffs',
  offices: '/api/v1/dashboard/offices',
  officesCity: '/api/v1/dashboard/office-cities',
  products: '/api/v1/devices',
  productsCategory: '/api/v1/device-catalogs',
  productsTags: '/api/v1/device-tags',
  banners: '/api/v1/dashboard/banners',
  faqs: '/api/v1/faqs',
  chatFaqs: '/api/faq/admin/v1',
  updateChatFaq: '/api/faq/admin/v1/update',
  chatFaqsCreate: '/api/faq/v1',
  services: '/api/v1/dashboard/services',
  serviceOptions: '/api/v1/dashboard/service-options',
  login: '/api/user/v1/registerOperator',

}
